apiVersion: v1
kind: PersistentVolume
metadata:
  name: node02-pv-1
  labels:
    app: mysql
spec:
  accessModes: [ ReadWriteOncePod ]
  capacity:
    storage: 1Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: kubernetes.io/hostname, operator: In, values: [node02]}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  volumeMode: Filesystem
  local:
    path: /mnt/kubernetes/pv-1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:9.0
        ports:
          - containerPort: 3306
            name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: laravel
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      os:
        name: linux
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ ReadWriteOncePod ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-storage
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
