apiVersion: v1
kind: Service
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  selector:
    app: laravel
  ports:
  - port: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: fpm
        image: glebsvitelskiy/laravel
        ports:
        - containerPort: 9000
          name: fpm
        envFrom:
        - configMapRef:
            name: laravel
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
            ephemeral-storage: 128Mi
        readinessProbe:
          httpGet:
            port: 80
            path: up
      initContainers:
      - name: copy-static-files
        image: glebsvitelskiy/laravel
        command: ['sh', '-c', 'cp --verbose --recursive public /mnt']
        volumeMounts:
        - mountPath: /mnt/public
          name: static-files
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
            ephemeral-storage: 128Mi
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-configuration
          readOnly: true
        - mountPath: /srv/laravel-app/public
          name: static-files
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
            ephemeral-storage: 128Mi
        restartPolicy: Always
      os:
        name: linux
      volumes:
      - name: static-files
        emptyDir:
          sizeLimit: 128Mi
      - name: nginx-configuration
        configMap:
          name: nginx
